apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: External-Secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: "external-secrets-sa"