apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-secret
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: External-Secret-store
    kind: SecretStore
  target:
    name: database-creds # K8s secret name
    creationPolicy: Owner
    template:
      type: Opaque # K8s secret type
  # Data to be stored in the K8s secret
  data:
    - secretKey: username # K8s secret key
      remoteRef:
        key: prod/db # AWS Secret manager key
        property: username # AWS Secret manager property
    - secretKey: password # K8s secret key
      remoteRef:
        key: prod/db # AWS Secret manager key
        property: password # AWS Secret manager property
