{{- range .Values.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
spec:
  refreshInterval: {{ .refreshInterval }}
  secretStoreRef:
    name: {{ .secretStoreRefName }}
    kind: {{ .secretStoreRefKind }}
  target:
    name: {{ .targetSecretName }}
    creationPolicy: Owner
    template:
      type: {{ .secretType }}
  data:
  {{- range .data }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteKey }}
        property: {{ .property }}
  {{- end }}
---
{{- end }}
