apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.nginxPod.name }}
  namespace: {{ .Values.nginxPod.namespace }}
spec:
  automountServiceAccountToken: false
  containers:
    - name: nginx
      image: {{ .Values.nginxPod.image }}
      resources:
        requests:
          memory: {{ .Values.nginxPod.resources.requests.memory }}
          cpu: {{ .Values.nginxPod.resources.requests.cpu }}
        limits:
          memory: {{ .Values.nginxPod.resources.limits.memory }}
          cpu: {{ .Values.nginxPod.resources.limits.cpu }}
      volumeMounts:
        {{- range .Values.nginxPod.secretNames }}
        - name: secret-volume-{{ . }}
          mountPath: /etc/secret-volume-{{ . }}
          readOnly: true
        {{- end }}
  volumes:
    {{- range .Values.nginxPod.secretNames }}
    - name: secret-volume-{{ . }}
      secret:
        secretName: {{ . }}
    {{- end }}
